version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  POSTGRES_VERSION_1: 15.4.1
  POSTGRES_VERSION_2: 15.4.2
  NAMESPACE: 05--postgresql

tasks:
  01-Create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens ${NAMESPACE}

  ### Helm repo
  02-add-repo:
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
    desc: Add Bitnami Helm repository    
  
  03-search-repo:
    desc: Search Bitnami repository for PostgreSQL
    cmds:
      - helm search repo bitnami/postgresql --versions 

  ### OCI registry
  04-login-oci-registry:
    desc: Login to OCI registry 
    cmds:
      - cmd: gum style "Use your dockerhub username and password!"
        silent: true
      - helm registry login registry-1.docker.io 

  05-list-registry:
    desc: List tags in the OCI registry
    cmds:
      - oras repo tags registry-1.docker.io/bitnamicharts/postgresql 

  06-pull:
    desc: Pull PostgreSQL chart from Bitnami repository
    cmds:
      - helm pull bitnami/postgresql --version=${POSTGRES_VERSION_2} 

  07-untar:
    desc: Untar PostgreSQL chart
    cmds:
      - tar -xzf postgresql-${POSTGRES_VERSION_2}.tgz

  08-show-values:
    desc: Show values for PostgreSQL chart
    cmds:
      - helm show values bitnami/postgresql --version=${POSTGRES_VERSION_2}

  09-install:
    desc: Install PostgreSQL chart
    cmds:
      - |
        helm install postgresql bitnami/postgresql \
          --version=${POSTGRES_VERSION_1} \
          --create-namespace \
          --values=values.yaml 

  10-upgrade:
    desc: Upgrade PostgreSQL chart
    cmds:
      - |
        helm upgrade --install postgresql bitnami/postgresql \
          --version=${POSTGRES_VERSION_2} \
          --create-namespace \
          --values=values.yaml

  11-rollback:
    desc: Rollback PostgreSQL chart  
    cmds:
      - helm rollback postgresql   

  12-list:
    desc: List Helm releases 
    cmds:
      - helm list -n ${NAMESPACE}  

  13-get-values:
    desc: Get values for PostgreSQL release
    cmds:
      - helm get values postgresql 

  14-get-manifests:
    desc: Get manifests for PostgreSQL release 
    cmds:
      - helm get manifest postgresql

  15-uninstall:
    desc: Uninstall PostgreSQL release
    cmds:
      - helm uninstall postgresql

  16-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - cmd: gum style "🚨 Deleting the namespace recursively deletes the resources inside of it! 🚨 "
        silent: true
      - kubectl delete -f Namespace.yaml    
                
