version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"

tasks:
### Helm installation
  01-Recovering-installation-script:  
    desc: "Recovering the installation script"
    cmds:
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

  02-Execution-rights:
    desc: "Let's give execution rights"
    cmds:
      - chmod 700 get_helm.sh

  03-Download-helm:
    desc: "Let's download helm"
    cmds:
      - ./get_helm.sh 

  04-Check-version:
    desc: "Let's check the version"
    cmds:
      - helm version   
 