version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: 04--pod

tasks:
  01-create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens ${NAMESPACE}

  01-Create-pod-def:
    desc: "Apply the pod-definition configuration"
    cmds:
      - kubectl apply -n ${NAMESPACE} -f pod-definition.yaml
      - kubectl get pods
        
  02-create-pod:
    desc: "Apply the minimal pod configuration"
    cmds:
      - kubectl apply -n ${NAMESPACE} -f pod.minimal-apply.yaml
      - kubectl get pods

  03-expose-port:
    desc: "Port forward minimal"
    cmds:
      - kubectl port-forward -n ${NAMESPACE} simple-webapp-color 8080:8080   

  04-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - cmd: gum style "🚨 Deleting the namespace recursively deletes the resources inside of it! 🚨 "
        silent: true
      - kubectl delete -f Namespace.yaml