version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: 04--service

tasks:
  01-create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens ${NAMESPACE}

  02-create-pod-red:
    desc: "Apply the Pod configuration"
    cmds:
      - kubectl apply -f pod-red.yaml

  03-create-pod-blue:
    desc: "Apply the Pod configuration"
    cmds:
      - kubectl apply -f pod-blue.yaml    

  04-create-service-nodeport:
    desc: "Apply the  NodePort Service"
    cmds:
      - kubectl apply -f service-nodeport-web.yaml

  05-expose-port:
    desc: "Port forward minimal"
    cmds:
      - kubectl port-forward svc/service-nodeport-web 8080:8080    

  06-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - cmd: gum style "🚨 Deleting the namespace recursively deletes the resources inside of it! 🚨 "
        silent: true
      - kubectl delete -f Namespace.yaml