apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-color-red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-red
  template:
    metadata:
      labels:
        app: web-red
    spec:
      containers:
      - name: web1
        image: mmumshad/simple-webapp-color  # Image pour le premier déploiement
        ports:
        - containerPort: 80
        env:
        - name: APP_COLOR
          value: red
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-color-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-blue
  template:
    metadata:
      labels:
        app: web-blue
    spec:
      containers:
      - name: web2
        image: mmumshad/simple-webapp-color  # Image pour le deuxième déploiement
        ports:
        - containerPort: 80
        env:
        - name: APP_COLOR
          value: blue
---
apiVersion: v1
kind: Service
metadata:
  name: web-red-service1
spec:
  selector:
    app: web-red
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-blue-service2
spec:
  selector:
    app: web-blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: web1.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-red-service1
            port:
              number: 80
  - host: web2.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-blue-service2
            port:
              number: 80

       
