version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: 04--replicasets
  NAME_REPLICAS: myapp-replicaset

tasks:
  01-create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens ${NAMESPACE}
        
  02-create-replicaset:
    desc: "Apply the replicasetconfiguration"
    cmds:
      - kubectl apply -n ${NAMESPACE} -f replicaset-definition.yaml
      - kubectl get replicaset
      - kubectl get pods

  03-Scale:
    desc: "Scale ReplicaSet"
    cmds:
      - kubectl scale replicaset ${NAME_REPLICAS} --replicas=2
      - kubectl get replicaset
      - kubectl get pods

  04-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - cmd: gum style "🚨 Deleting the namespace recursively deletes the resources inside of it! 🚨 "
        silent: true
      - kubectl delete -f Namespace.yaml